In [3]:
# !pip install pandas
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv("data.csv")

In [5]:
df.head(2)

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,11.28,0.90,34,23,1,1,0,45961,48071,250,2,1,1
1,0,9.75,0.23,54,33,1,0,0,26106,25333,205,3,0,0

In [6]:
df.tail(2)

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
1998,0,11.15,0.72,46,45,1,0,1,18157,15275,253,3,0,1
1999,1,11.36,0.09,41,45,0,0,0,20729,30463,230,1,1,0

In [7]:
df.columns

Index(['Blood_Pressure_Abnormality', 'Level_of_Hemoglobin',
       'Genetic_Pedigree_Coefficient', 'Age', 'BMI', 'Sex', 'Pregnancy',
       'Smoking', 'Physical_activity', 'salt_content_in_the_diet',
       'alcohol_consumption_per_day', 'Level_of_Stress',
       'Chronic_kidney_disease', 'Adrenal_and_thyroid_disorders'],
      dtype='object')

In [8]:
df.count()

Blood_Pressure_Abnormality       2000
Level_of_Hemoglobin              2000
Genetic_Pedigree_Coefficient     2000
Age                              2000
BMI                              2000
Sex                              2000
Pregnancy                        2000
Smoking                          2000
Physical_activity                2000
salt_content_in_the_diet         2000
alcohol_consumption_per_day      2000
Level_of_Stress                  2000
Chronic_kidney_disease           2000
Adrenal_and_thyroid_disorders    2000
dtype: int64

In [9]:
df.describe()

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.0000,2000.000000
mean,0.493500,11.710035,0.494595,46.558500,30.081500,0.496000,0.099500,0.509500,25254.424500,24926.097000,250.886500,2.012500,0.5050,0.443500
std,0.500083,2.186701,0.284945,17.107832,11.761208,0.500109,0.299407,0.500035,14015.439623,14211.692586,134.676589,0.823822,0.5001,0.496922
min,0.000000,8.100000,0.000000,18.000000,10.000000,0.000000,0.000000,0.000000,628.000000,22.000000,0.000000,1.000000,0.0000,0.000000
25%,0.000000,10.147500,0.250000,32.000000,20.000000,0.000000,0.000000,0.000000,13605.750000,13151.750000,144.000000,1.000000,0.0000,0.000000
50%,0.000000,11.330000,0.490000,46.000000,30.000000,0.000000,0.000000,1.000000,25353.000000,25046.500000,250.000000,2.000000,1.0000,0.000000
75%,1.000000,12.945000,0.730000,62.000000,40.000000,1.000000,0.000000,1.000000,37382.250000,36839.750000,360.250000,3.000000,1.0000,1.000000
max,1.000000,17.560000,1.000000,75.000000,50.000000,1.000000,1.000000,1.000000,49980.000000,49976.000000,499.000000,3.000000,1.0000,1.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Blood_Pressure_Abnormality     2000 non-null   int64
 1   Level_of_Hemoglobin            2000 non-null   float64
 2   Genetic_Pedigree_Coefficient   2000 non-null   float64
 3   Age                            2000 non-null   int64
 4   BMI                            2000 non-null   int64
 5   Sex                            2000 non-null   int64
 6   Pregnancy                      2000 non-null   int64
 7   Smoking                        2000 non-null   int64
 8   Physical_activity              2000 non-null   int64
 9   salt_content_in_the_diet       2000 non-null   int64
 10  alcohol_consumption_per_day    2000 non-null   int64
 11  Level_of_Stress                2000 non-null   int64
 12  Chronic_kidney_disease         2000 non-null   int64
 13  Adrenal_and_thyroid_disorders  2000 non-null   int64
dtypes: float64(2), int64(12)
memory usage: 218.9 KB

In [11]:
df['Age'].unique()

array([34, 54, 70, 71, 52, 23, 43, 48, 72, 40, 35, 31, 75, 18, 65, 61, 36,
       27, 66, 38, 55, 58, 69, 25, 39, 42, 21, 24, 53, 51, 74, 46, 28, 32,
       63, 20, 56, 45, 44, 19, 68, 73, 30, 22, 47, 59, 64, 50, 67, 62, 57,
       60, 49, 33, 29, 37, 26, 41], dtype=int64)

In [12]:
df.nunique()

Blood_Pressure_Abnormality          2
Level_of_Hemoglobin               757
Genetic_Pedigree_Coefficient      101
Age                                58
BMI                                41
Sex                                 2
Pregnancy                           2
Smoking                             2
Physical_activity                1951
salt_content_in_the_diet         1945
alcohol_consumption_per_day       488
Level_of_Stress                     3
Chronic_kidney_disease              2
Adrenal_and_thyroid_disorders       2
dtype: int64

In [13]:
df.isnull().sum()

Blood_Pressure_Abnormality       0
Level_of_Hemoglobin              0
Genetic_Pedigree_Coefficient     0
Age                              0
BMI                              0
Sex                              0
Pregnancy                        0
Smoking                          0
Physical_activity                0
salt_content_in_the_diet         0
alcohol_consumption_per_day      0
Level_of_Stress                  0
Chronic_kidney_disease           0
Adrenal_and_thyroid_disorders    0
dtype: int64